language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t erickc80/docker-react -f ./Dockerfile.dev ./

script:
    - docker run -e CI=true erickc80/docker-react npm run test